name: .NET Build and Test

on:
  push:
    branches: [ main, develop, release ]
  pull_request:
    branches: [ main, develop, release ]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Restore tools
        run: dotnet tool restore
        
      - name: Build
        run: dotnet build --no-restore

      - name: Install playwright
        run: dotnet pwsh tests/Chirp.WebService.Tests/bin/Debug/net7.0/playwright.ps1 install
        
      - name: Test
        run: dotnet test --no-build --verbosity normal