name: .NET Publish App
permissions:
  contents: write
on:
  release:
    types: [ published ]

jobs:
  ReleaseApp:
    strategy:
      matrix:
        kind: [ 'linux-x64', 'win-x64', 'win-x86', 'win-arm64', 'osx-x64', 'osx-arm64' ]
        include:
          - kind: linux-x64
            os: ubuntu-latest
            target: linux-x64
          - kind: win-x64
            os: windows-latest
            target: win-x64
          - kind: win-x86
            os: windows-latest
            target: win-x86
          - kind: win-arm64
            os: windows-latest
            target: win-arm64
          - kind: osx-x64
            os: macos-latest
            target: osx-x64
          - kind: osx-arm64
            os: macos-latest
            target: osx-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build
        shell: bash
        run: |
          # Define some variables for things we need
          tag=$(git describe --tags --abbrev=0)
          release_name="Chirp-$tag-${{ matrix.target }}"

          # Build everything
          dotnet publish src/Chirp.CLI.Client/Chirp.CLI.Client.csproj --framework net7.0 --runtime "${{ matrix.target }}" --self-contained false -c Release -o "$release_name"

          # Pack files
#          if [ "${{ matrix.os }}" == "windows-latest" ]; then
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
#          else
#            tar czvf "${release_name}.tar.gz" "$release_name"
#          fi

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
#            Chirp-*.tar.gz
            Chirp-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}