name: Build Project Report

on:
  - push
  - pull_request

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
      infra: ${{ steps.changes.outputs.infra }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Filter paths
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |     
            report:
              - 'docs/report.md'
              - 'docs/images/*'
              - 'docs/diagrams/*'
        
  buildReport:
    needs: changes
    if: ${{ needs.changes.outputs.report == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Update apt-get
        run: sudo apt-get update

      - name: Get tex and pandoc packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: pandoc texlive-base texlive-latex-recommended texlive-fonts-recommended
          version: 1.0

      - name: Generate report pdf
        run: pandoc docs/report.md -o docs/2023_itubdsa_group_11_report.pdf
        
      - name: Add report as its own commit
        run: |
          git add .
          git commit -m "Formatted report"
          git push