name: Build Project Report

permissions:
  contents: write
  pull-requests: write

on: push

jobs:
  pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        

      - name: Install tex tool
        run: |
          sudo apt-get update
          sudo apt-get install texlive-latex-base
          sudo apt-get install pdf-latex
      
      - name: Convert md to pdf
        uses: docker://pandoc/core:2.9
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --pdf-engine=pdflatex
            --output=docs/2023_itubdsa_group_11_report.pdf
            -f markdown
            -t pdf
            docs/report.md