name: Build Project Report

permissions:
  contents: write
  pull-requests: write

on: push

jobs:
  pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - run: sudo apt-get update
          
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: texlive-base texlive-xetex pandoc
          version: 1.0
          
      - run: pandoc --version
      
      - run: pandoc --pdf-engine=pdflatex --output=docs/2023_itubdsa_group_11_report.pdf -f markdown -t pdf docs/report.md