name: Build Project Report

on:
  pull_request:
    branches: [ main ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      report: ${{ steps.changes.outputs.report }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Filter paths
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |     
            report:
              - 'docs/report.md'
              - 'docs/images/*'
              - 'docs/diagrams/*'
        
  buildReport:
    needs: changes
    if: ${{ needs.changes.outputs.report == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Update apt-get
        run: sudo apt-get update
      
      - name: Install tex and pandoc packages with apt-get
        run: |
          sudo apt-get install -y --reinstall pandoc
          sudo apt-get install -y --reinstall texlive-base
          sudo apt-get install -y --reinstall texlive-latex-recommended
          sudo apt-get install -y --reinstall texlive-fonts-recommended

      - name: Generate report pdf
        run: pandoc docs/report.md -o docs/2023_itubdsa_group_11_report.pdf
        
      - name: Add report as its own commit
        run: |
          git config --global user.email "reportgenerator@bdsagroup11.dk"
          git config --global user.name "Report Generator"
          git add .
          git commit -m "Formatted report"
          git push