name: Build Project Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-if-report-changed:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
      infra: ${{ steps.changes.outputs.infra }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |     
            report:
              - 'docs/report.md'
              - 'docs/images/*'
              - 'docs/diagrams/*'
        
  buildReport:
    needs: changes
    if: ${{ needs.changes.outputs.report == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - if: steps.changes.outputs.report == 'true'
        run: sudo apt-get update

      - if: steps.changes.outputs.report == 'true'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: pandoc texlive-base texlive-latex-recommended texlive-fonts-recommended
          version: 1.0

      - if: steps.changes.outputs.report == 'true'
        run: pandoc docs/report.md -o docs/2023_itubdsa_group_11_report.pdf
        
      - run: |
          git add .
          git commit -m "Formatted report"
          git push