name: Build Project Report

on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    name: Check for report changes
    runs-on: ubuntu-latest
    outputs:
      report: ${{ steps.changes.outputs.report }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Filter paths
        uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ github.ref }}
          filters: |     
            report:
              - 'docs/report.md'
              - 'docs/images/*'
              - 'docs/diagrams/*'
        
  buildReport:
    name: Build Report
    needs: changes
    if: ${{ needs.changes.outputs.report == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.ACTIONS_PAT }}
        
      - name: Update apt-get
        run: sudo apt-get update
      
      - name: Install tex and pandoc packages with apt-get
        run: |
          sudo apt-get install -y --reinstall pandoc
          sudo apt-get install -y --reinstall texlive-base
          sudo apt-get install -y --reinstall texlive-latex-recommended
          sudo apt-get install -y --reinstall texlive-fonts-recommended

      - name: Generate report pdf
        run: pandoc docs/report.md -o docs/2023_itubdsa_group_11_report.pdf --highlight-style=tango
        
      - uses: EndBug/add-and-commit@v9
        with:
          # The arguments for the `git add` command
          add: '.'

          # Determines the way the action fills missing author name and email.
          default_author: github_actions

          # Arguments for the git fetch command. If set to false, the action won't fetch the repo.
          fetch: false

          # The message for the commit.
          message: 'Built report pdf'

          # Whether to push the commit and, if any, its tags to the repo.
          push: true