name: Test Coverage

on:
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x  

      - name: Build and run tests
        run: |
          dotnet build
          dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Generate code coverage report
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator "-reports:./**/coverage.opencover.xml" "-targetdir:coverage" -reporttypes:Html

      - name: Check code coverage
        id: check_coverage
        run: |
          $threshold=40
          $actual=$(gcovr -r . --xml | [xml]::new().Load(Console.In))
          $coverage=[float]($actual.SelectSingleNode('//line-rate').InnerText) * 100
          echo "Code coverage: $coverage%"
          if ($coverage -lt $threshold) { exit 1 }

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage

  coverage:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage-report

      - name: Publish code coverage
        uses: codecov/codecov-action@v2
